import { useState } from "react";
import {
  PenTool,
  Layout,
  Sparkles,
  ArrowRight,
  Send,
} from "lucide-react";
import type { DashboardPage } from "../Sidebar";

interface DesignPageProps {
  onNavigate: (page: DashboardPage) => void;
}

export default function DesignPage({ onNavigate }: DesignPageProps) {
  const [aiPrompt, setAiPrompt] = useState("");
  const [aiResponse, setAiResponse] = useState("");
  const [isGenerating, setIsGenerating] = useState(false);

  const handleGenerate = () => {
    if (!aiPrompt.trim()) return;
    setIsGenerating(true);
    setAiResponse("");
    // Simulate AI response
    setTimeout(() => {
      setAiResponse(
        `Great idea! Here's what I can create for you based on "${aiPrompt}":\n\n• A custom 3D model with optimized geometry\n• Recommended material: PLA or Resin for best detail\n• Estimated print time: 2-4 hours\n• Suggested infill: 20-40%\n\nWould you like me to generate a preview?`
      );
      setIsGenerating(false);
    }, 2000);
  };

  return (
    <div className="dashboard-page">
      <div className="dashboard-page-header">
        <h2>Create Your Design</h2>
        <p>Use our easy tools to design something unique.</p>
      </div>

      <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 24 }}>
        {/* Left - Design Options */}
        <div>
          <div style={{ display: "flex", flexDirection: "column", gap: 12, marginBottom: 28 }}>
            <div
              className="dash-design-option"
              onClick={() => onNavigate("upload")}
            >
              <div className="option-icon">
                <PenTool size={18} />
              </div>
              <div>
                <div className="option-title">Start from Scratch</div>
                <div className="option-desc">
                  Create your own design by uploading an STL, OBJ, or 3MF file.
                </div>
              </div>
            </div>

            <div
              className="dash-design-option"
              onClick={() => onNavigate("our-designs")}
            >
              <div className="option-icon">
                <Layout size={18} />
              </div>
              <div>
                <div className="option-title">Choose Template</div>
                <div className="option-desc">
                  Pick a template and customize it with your text, colors, and dimensions.
                </div>
              </div>
            </div>

            <div className="dash-design-option" onClick={() => document.getElementById("ai-prompt-input")?.focus()}>
              <div className="option-icon">
                <Sparkles size={18} />
              </div>
              <div>
                <div className="option-title">AI Design Assistant</div>
                <div className="option-desc">
                  Describe your idea and get a concept preview generated by AI.
                </div>
              </div>
            </div>
          </div>

          <button className="dash-btn-primary" onClick={() => onNavigate("upload")}>
            Start Designing <ArrowRight size={16} />
          </button>
        </div>

        {/* Right - 3D Preview / Rocket Placeholder */}
        <div>
          <div
            className="dash-3d-preview"
            style={{
              display: "flex",
              alignItems: "center",
              justifyContent: "center",
              aspectRatio: "4/3",
              background:
                "radial-gradient(ellipse at center, rgba(var(--accent-rgb), 0.06) 0%, #0A0A0A 70%)",
            }}
          >
            {/* SVG Rocket placeholder */}
            <svg viewBox="0 0 200 280" width="140" height="200" style={{ filter: "drop-shadow(0 0 20px rgba(var(--accent-rgb), 0.3))" }}>
              {/* Rocket body */}
              <defs>
                <linearGradient id="rocketGrad" x1="0%" y1="0%" x2="100%" y2="100%">
                  <stop offset="0%" stopColor="var(--accent)" stopOpacity="0.9" />
                  <stop offset="100%" stopColor="#FF8A3D" stopOpacity="0.9" />
                </linearGradient>
                <linearGradient id="windowGrad" x1="0%" y1="0%" x2="0%" y2="100%">
                  <stop offset="0%" stopColor="#00E5FF" stopOpacity="0.8" />
                  <stop offset="100%" stopColor="#0066FF" stopOpacity="0.6" />
                </linearGradient>
              </defs>
              {/* Nose cone */}
              <path d="M100 10 L130 80 L70 80 Z" fill="url(#rocketGrad)" />
              {/* Body */}
              <rect x="70" y="80" width="60" height="120" rx="4" fill="#1a1a1a" stroke="var(--accent)" strokeWidth="1" strokeOpacity="0.3" />
              {/* Window */}
              <circle cx="100" cy="125" r="18" fill="url(#windowGrad)" stroke="var(--accent)" strokeWidth="1.5" strokeOpacity="0.5" />
              <circle cx="100" cy="125" r="12" fill="#0A0A0A" stroke="#00E5FF" strokeWidth="0.5" strokeOpacity="0.3" />
              {/* Fins */}
              <path d="M70 170 L45 220 L70 200 Z" fill="url(#rocketGrad)" opacity="0.8" />
              <path d="M130 170 L155 220 L130 200 Z" fill="url(#rocketGrad)" opacity="0.8" />
              {/* Exhaust */}
              <ellipse cx="100" cy="210" rx="20" ry="6" fill="var(--accent)" opacity="0.3" />
              <rect x="85" y="200" width="30" height="15" rx="2" fill="#222" stroke="#333" strokeWidth="0.5" />
              {/* Flame */}
              <path d="M85 215 Q100 260 115 215" fill="var(--accent)" opacity="0.5">
                <animate attributeName="d" values="M85 215 Q100 260 115 215;M88 215 Q100 250 112 215;M85 215 Q100 260 115 215" dur="0.5s" repeatCount="indefinite" />
              </path>
              <path d="M90 215 Q100 245 110 215" fill="#FF8A3D" opacity="0.7">
                <animate attributeName="d" values="M90 215 Q100 245 110 215;M92 215 Q100 238 108 215;M90 215 Q100 245 110 215" dur="0.4s" repeatCount="indefinite" />
              </path>
              {/* Detail lines */}
              <line x1="70" y1="100" x2="130" y2="100" stroke="var(--accent)" strokeWidth="0.5" strokeOpacity="0.2" />
              <line x1="70" y1="160" x2="130" y2="160" stroke="var(--accent)" strokeWidth="0.5" strokeOpacity="0.2" />
              {/* Rivets */}
              <circle cx="76" cy="90" r="2" fill="var(--accent)" opacity="0.3" />
              <circle cx="124" cy="90" r="2" fill="var(--accent)" opacity="0.3" />
              <circle cx="76" cy="190" r="2" fill="var(--accent)" opacity="0.3" />
              <circle cx="124" cy="190" r="2" fill="var(--accent)" opacity="0.3" />
            </svg>

            {/* 3D Controls */}
            <div className="dash-3d-controls">
              <button title="Rotate Left">↺</button>
              <button title="Zoom In">+</button>
              <button title="Zoom Out">−</button>
              <button title="Rotate Right">↻</button>
            </div>
          </div>
        </div>
      </div>

      {/* AI Assistant Section */}
      <div
        className="dash-card"
        style={{
          marginTop: 28,
          borderColor: "rgba(var(--accent-rgb), 0.15)",
          background: "#0D0D0D",
        }}
      >
        <div
          style={{
            display: "flex",
            alignItems: "center",
            gap: 8,
            marginBottom: 16,
          }}
        >
          <Sparkles size={16} style={{ color: "var(--accent)" }} />
          <span
            style={{
              fontFamily: "'Rajdhani', sans-serif",
              fontWeight: 700,
              fontSize: "0.9rem",
              color: "#fff",
              textTransform: "uppercase",
              letterSpacing: "0.06em",
            }}
          >
            Describe Your Idea (AI Assistant)
          </span>
        </div>

        <div style={{ display: "flex", gap: 12, marginBottom: aiResponse ? 16 : 0 }}>
          <input
            id="ai-prompt-input"
            type="text"
            className="dash-input"
            placeholder="Example: A keychain with name Rahul in cursive font..."
            value={aiPrompt}
            onChange={(e) => setAiPrompt(e.target.value)}
            onKeyDown={(e) => e.key === "Enter" && handleGenerate()}
            style={{ flex: 1 }}
          />
          <button
            className="dash-btn-primary"
            onClick={handleGenerate}
            disabled={isGenerating}
            style={{ whiteSpace: "nowrap" }}
          >
            {isGenerating ? (
              "Generating..."
            ) : (
              <>
                Generate Preview <Send size={14} />
              </>
            )}
          </button>
        </div>

        {aiResponse && (
          <div
            style={{
              background: "#111",
              border: "1px solid #1a1a1a",
              borderRadius: 8,
              padding: 16,
              fontFamily: "'DM Mono', monospace",
              fontSize: "0.75rem",
              color: "#aaa",
              lineHeight: 1.7,
              whiteSpace: "pre-wrap",
            }}
          >
            {aiResponse}
          </div>
        )}
      </div>
    </div>
  );
}
